name: terraform-network

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  call-workflow:
    uses: goodsystems/reusable-workflows-terraform-aws/.github/workflows/reusable-workflows-terraform-aws.yml@v4
    with:
      project: "terraform-network"
